// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package runtime

import (
	"github.com/things-go/ormat/pkg/config"
)

// Injectors from wire.go:

func NewRuntime(c *config.Config) (*Runtime, error) {
	database := NewDbConfig(c)
	db, err := NewDb(database)
	if err != nil {
		return nil, err
	}
	runtime := &Runtime{
		DB: db,
	}
	return runtime, nil
}
