// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package runtime

// Injectors from wire.go:

func NewRuntime(remote bool) (*Runtime, error) {
	config, err := NewConfig(remote)
	if err != nil {
		return nil, err
	}
	database := NewDbConfig(config)
	db, err := NewDb(remote, database)
	if err != nil {
		return nil, err
	}
	runtime := &Runtime{
		Config: config,
		DB:     db,
	}
	return runtime, nil
}
