// Code generated by ormat. DO NOT EDIT.
// version: {{.Version}}

package {{.PackageName}}

import (
	assist "github.com/things-go/gorm-assist"
    "gorm.io/gorm"
)

{{- range $e := .Structs}}

// X_{{$e.StructName}}_Executor executor suggest use only once
func X_{{$e.StructName}}_Executor(db *gorm.DB) *assist.Executor[{{$e.StructName}}] {
	return assist.NewExecutor[{{$e.StructName}}](db)
}

{{- end}}