// Code generated by ormat. DO NOT EDIT.
// version: {{.Version}}

syntax = "proto3";

package {{.Package}};
{{- range $k, $v := .Options}}
option {{$k}} = "{{$v}}";
{{- end}}

{{- range $e := .Enums}}
// {{$e.EnumName}} {{$e.EnumComment}}
enum {{$e.EnumName}} {
{{- range $ee := $e.EnumFields}}
  {{- if $ee.Comment}}
  // {{$ee.Comment}}
  {{- end}}
  {{$ee.Name}} = {{$ee.Id}};
{{- end}}
}
{{- end}}