// Code generated by ormat. DO NOT EDIT.
// version: v0.1.0

package testdata

import (
	"time"
)

// TestData 公告-面向所有人的消息
type TestData struct {
	Id        int64     `gorm:"column:id;autoIncrement:true;not null;primaryKey" json:"id,omitempty"`
	Title     string    `gorm:"column:title;type:varchar(255);not null;index:uk_title_created_at,priority:1;comment:标题" json:"title,omitempty"`                                                                                                 // 标题
	Content   string    `gorm:"column:content;type:varchar(2048);not null;comment:内容" json:"content,omitempty"`                                                                                                                                 // 内容
	Value1    float32   `gorm:"column:value1;type:float;not null;default:1;comment:[@enum:{\"0\":[\"none\",\"空\",\"空注释\"],\"1\":[\"key1\",\"键1\",\"键1注释\"],\"2\":[\"key2\",\"键2\"],\"3\":[\"key3\",\"键3\"]}]" json:"value1,omitempty"`          // [@enum:{"0":["none","空","空注释"],"1":["key1","键1","键1注释"],"2":["key2","键2"],"3":["key3","键3"]}]
	Value2    float32   `gorm:"column:value2;type:float(10,1);not null;default:2;comment:值2,[@enum:{\"0\":[\"none\",\"空\",\"空注释\"],\"1\":[\"key1\",\"键1\",\"键1注释\"],\"2\":[\"key2\",\"键2\"],\"3\":[\"key3\",\"键3\"]}]" json:"value2,omitempty"` // 值2,[@enum:{"0":["none","空","空注释"],"1":["key1","键1","键1注释"],"2":["key2","键2"],"3":["key3","键3"]}]
	Value3    string    `gorm:"column:value3;type:enum('00','SH');not null;default:4;comment:值4" json:"value3,omitempty"`                                                                                                                       // 值4
	CreatedAt time.Time `gorm:"column:created_at;type:datetime;not null;index:uk_title_created_at,priority:2;comment:发布时间" json:"created_at,omitempty"`                                                                                         // 发布时间
	UpdatedAt time.Time `gorm:"column:updated_at;type:datetime;not null" json:"updated_at,omitempty"`
}

// TableName implement schema.Tabler interface
func (*TestData) TableName() string {
	return "test_data"
}

// __TestDataValue1Mapping  TestDataValue1 mapping
var __TestDataValue1Mapping = map[int]string{
	0: "空",
	1: "键1",
	2: "键2",
	3: "键3",
}

// GetTestDataValue1Desc get mapping description
func GetTestDataValue1Desc(t int) string {
	return __TestDataValue1Mapping[t]
}

// __TestDataValue2Mapping  TestDataValue2 mapping
var __TestDataValue2Mapping = map[int]string{
	0: "空",
	1: "键1",
	2: "键2",
	3: "键3",
}

// GetTestDataValue2Desc get mapping description
func GetTestDataValue2Desc(t int) string {
	return __TestDataValue2Mapping[t]
}

/* protobuf and gorm field helper
// TestDataColumns database column name.
var TestDataColumns = []string {
	"id",
	"title",
	"content",
	"value1",
	"value2",
	"value2",
	"value3",
	"created_at",
	"UNIX_TIMESTAMP(created_at) AS created_at",
	"updated_at",
	"UNIX_TIMESTAMP(updated_at) AS updated_at",
}
// TestDataColumnsWithTable database column name with table prefix
var TestDataColumnsWithTable = []string {
	"test_data.id AS test_data_id",
	"test_data.title AS test_data_title",
	"test_data.content AS test_data_content",
	"test_data.value1 AS test_data_value1",
	"test_data.value2 AS test_data_value2",
	"test_data.value2 AS test_data_value2",
	"test_data.value3 AS test_data_value3",
	"test_data.created_at AS test_data_created_at",
	"UNIX_TIMESTAMP(test_data.created_at) AS test_data_created_at",
	"test_data.updated_at AS test_data_updated_at",
	"UNIX_TIMESTAMP(test_data.updated_at) AS test_data_updated_at",
}
// TestDataColumnsWithAbbrTable database column name with abbr table prefix
var TestDataColumnsWithAbbrTable = []string {
	"td.id AS td_id",
	"td.title AS td_title",
	"td.content AS td_content",
	"td.value1 AS td_value1",
	"td.value2 AS td_value2",
	"td.value2 AS td_value2",
	"td.value3 AS td_value3",
	"td.created_at AS td_created_at",
	"UNIX_TIMESTAMP(td.created_at) AS td_created_at",
	"td.updated_at AS td_updated_at",
	"UNIX_TIMESTAMP(td.updated_at) AS td_updated_at",
}

// TestData 公告-面向所有人的消息
message TestData {
	int64 id = 1 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { type: [ INTEGER ] }];
	// 标题
	string title = 2;
	// 内容
	string content = 3;
	// [@enum:{"0":["none","空","空注释"],"1":["key1","键1","键1注释"],"2":["key2","键2"],"3":["key3","键3"]}]
	float value1 = 4;
	// 值2,[@enum:{"0":["none","空","空注释"],"1":["key1","键1","键1注释"],"2":["key2","键2"],"3":["key3","键3"]}]
	float value2 = 5;
	// 值3
	double value2 = 6;
	// 值4
	string value3 = 7;
	// 发布时间
	google.protobuf.Timestamp created_at = 8 [(gogoproto.stdtime) = true, (gogoproto.nullable) = false];
	// 发布时间
	int64 created_at = 9 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { type: [ INTEGER ] }];
	google.protobuf.Timestamp updated_at = 10 [(gogoproto.stdtime) = true, (gogoproto.nullable) = false];
	int64 updated_at = 11 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { type: [ INTEGER ] }];
}
// TestDataWithTable 公告-面向所有人的消息
message TestDataWithTable {
	int64 test_data_id = 1 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { type: [ INTEGER ] }];
	// 标题
	string test_data_title = 2;
	// 内容
	string test_data_content = 3;
	// [@enum:{"0":["none","空","空注释"],"1":["key1","键1","键1注释"],"2":["key2","键2"],"3":["key3","键3"]}]
	float test_data_value1 = 4;
	// 值2,[@enum:{"0":["none","空","空注释"],"1":["key1","键1","键1注释"],"2":["key2","键2"],"3":["key3","键3"]}]
	float test_data_value2 = 5;
	// 值3
	double test_data_value2 = 6;
	// 值4
	string test_data_value3 = 7;
	// 发布时间
	google.protobuf.Timestamp test_data_created_at = 8 [(gogoproto.stdtime) = true, (gogoproto.nullable) = false];
	// 发布时间
	int64 test_data_created_at = 9 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { type: [ INTEGER ] }];
	google.protobuf.Timestamp test_data_updated_at = 10 [(gogoproto.stdtime) = true, (gogoproto.nullable) = false];
	int64 test_data_updated_at = 11 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { type: [ INTEGER ] }];
}
// TestDataWithAbbrTable 公告-面向所有人的消息
message TestDataWithAbbrTable {
	int64 td_id = 1 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { type: [ INTEGER ] }];
	// 标题
	string td_title = 2;
	// 内容
	string td_content = 3;
	// [@enum:{"0":["none","空","空注释"],"1":["key1","键1","键1注释"],"2":["key2","键2"],"3":["key3","键3"]}]
	float td_value1 = 4;
	// 值2,[@enum:{"0":["none","空","空注释"],"1":["key1","键1","键1注释"],"2":["key2","键2"],"3":["key3","键3"]}]
	float td_value2 = 5;
	// 值3
	double td_value2 = 6;
	// 值4
	string td_value3 = 7;
	// 发布时间
	google.protobuf.Timestamp td_created_at = 8 [(gogoproto.stdtime) = true, (gogoproto.nullable) = false];
	// 发布时间
	int64 td_created_at = 9 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { type: [ INTEGER ] }];
	google.protobuf.Timestamp td_updated_at = 10 [(gogoproto.stdtime) = true, (gogoproto.nullable) = false];
	int64 td_updated_at = 11 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { type: [ INTEGER ] }];
}
*/

/*
// TestDataValue1 [@enum:{"0":["none","空","空注释"],"1":["key1","键1","键1注释"],"2":["key2","键2"],"3":["key3","键3"]}]
enum TestDataValue1 {
	// 空,空注释
	TEST_DATA_VALUE1_NONE = 0;
	// 键1,键1注释
	TEST_DATA_VALUE1_KEY1 = 1;
	// 键2
	TEST_DATA_VALUE1_KEY2 = 2;
	// 键3
	TEST_DATA_VALUE1_KEY3 = 3;
}
// TestDataValue2 值2,[@enum:{"0":["none","空","空注释"],"1":["key1","键1","键1注释"],"2":["key2","键2"],"3":["key3","键3"]}]
enum TestDataValue2 {
	// 空,空注释
	TEST_DATA_VALUE2_NONE = 0;
	// 键1,键1注释
	TEST_DATA_VALUE2_KEY1 = 1;
	// 键2
	TEST_DATA_VALUE2_KEY2 = 2;
	// 键3
	TEST_DATA_VALUE2_KEY3 = 3;
}
*/
